frr version 10.0
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
rpki
 rpki polling_period 10
 rpki retry_interval 1
 rpki cache 10.0.25.2 8282 preference 1
 exit
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.23.2 remote-as 65003
 neighbor 10.0.24.2 remote-as 65004
 !
 address-family ipv4 unicast
 exit-address-family
!
line vty
