// Authoritative-only config for the example.lab. server (Lab 05).
options {
    directory "/var/cache/bind";
    recursion no;
    allow-query { any; };
    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
    minimal-responses no;
};

logging {
    channel stderrlog {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
    };
    category default { stderrlog; };
    category queries { stderrlog; };
};

zone "example.lab." {
    type master;
    file "/etc/bind/db.example.lab";
};
